### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by p1d1d1** [OpenTransport/linked-gtfs#12]
Using gtfs:routeType and gtfs:agency as property of gtfs:Stop would not be correct, right?
Actually my data model would fit into this possibility, I mean I have stops and I want to associate to each stop the service provider and the means of transportation.
How to proceed

**Comment by pietercolpaert** [comment]
Hi @p1d1d1 - This indeed does not fit the ontology of GTFS as described by the original specification. The goal of this project is to indeed have a 1 on 1 mapping between this specification and the Linked Data world.

How to proceed: or you can look for different ontologies that could fit your data model, or you could create your own. By creating your own, you can still refer to the GTFS terms and say, for instance, there’s a skos:closeMatch.

**Comment by p1d1d1** [comment]
@pietercolpaert will you consider for the future the vehicle_type extension?
https://developers.google.com/transit/gtfs/reference/gtfs-extensions#station-vehicle-types

**Comment by pietercolpaert** [comment]
I will merge all pull requests with official specification!
